export default function register(ctx){
  const { router, state, renderShell } = ctx;
  router.register("dashboard",()=>{
    const m=state.metrics(); const attention=state.attentionItems().slice(0,5);
    const score=m.total?Math.round(((m.complete+m.discussion*.55+m.amendment*.35)/m.total)*100):0;
    const rows=attention.length?attention.map(item=>`<button class="attention-row" data-open-direct="${item.articleIndex}:${item.sectionIndex}"><span class="attention-mark ${item.review.status}"></span><span><strong>Section ${item.section.number} — ${item.section.title}</strong><small>${item.review.status==="amendment"?"Amendment recommended":"Board discussion required"}</small></span><span>›</span></button>`).join(""):`<div class="empty-state">Nothing currently requires immediate governance attention.</div>`;
    renderShell(`<section class="hero"><div class="eyebrow">Temple Board Workspace</div><h1>Good ${state.greeting()}, Ryan.</h1><p>This build adds permanent review records, institutional knowledge, related records, and live governance attention tracking.</p><div class="rule"></div></section><section class="health-card"><div><span>Governance Health</span><strong>${score}%</strong><small>Internal completion indicator — not a legal certification</small></div><div class="health-ring" style="--score:${score}"><b>${score}</b></div></section><section class="summary-grid"><article class="summary-card"><span>Governance Review</span><strong>${m.reviewed} / ${m.total}</strong><small>sections reviewed</small></article><article class="summary-card"><span>Progress</span><strong>${m.percent}%</strong><small>${m.total-m.reviewed} remaining</small><div class="progress-track"><i style="width:${m.percent}%"></i></div></article><article class="summary-card"><span>Discussion</span><strong>${m.discussion}</strong><small>sections</small></article><article class="summary-card"><span>Amendments</span><strong>${m.amendment}</strong><small>recommended</small></article></section><section class="panel"><div class="panel-head"><div><h2>${state.reviewYear} Governance Review</h2><p>${state.articles.length} Articles · ${m.total} Sections</p></div><button class="btn" data-route="review">${m.reviewed?"Continue Review":"Begin Review"}</button></div><div class="panel-body"><button class="menu-row" data-route="review"><span><span class="row-title">Corporate By-Laws</span><span class="row-sub">Review all Articles and Sections.</span></span></button><button class="menu-row" data-route="export"><span><span class="row-title">Review Data & Publication</span><span class="row-sub">Back up CORE or generate the ORE review file.</span></span></button><button class="menu-row" data-route="settings"><span><span class="row-title">Platform & Modules</span><span class="row-sub">View installed modules, versions, and system health.</span></span></button></div></section><section class="panel"><div class="panel-head"><div><h2>Attention Required</h2><p>Discussion and amendment records</p></div></div><div class="panel-body">${rows}</div></section>`,"dashboard");
  });
  document.addEventListener("click",e=>{const d=e.target.closest("[data-open-direct]"); if(!d)return; const [a,s]=d.dataset.openDirect.split(":").map(Number); ctx.events.emit("review:open-direct",{articleIndex:a,sectionIndex:s});});
}
